_FIRST_MUTABLE = dict(
    _scope_='mmrazor',
    candidates=dict(
        mb_k3e1=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=1,
            kernel_size=3,
            type='MBBlock')),
    type='OneShotMutableOP')
_STAGE_MUTABLE = dict(
    _scope_='mmrazor',
    candidates=dict(
        identity=dict(type='Identity'),
        mb_k3e3=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=3,
            kernel_size=3,
            type='MBBlock'),
        mb_k3e6=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=6,
            kernel_size=3,
            type='MBBlock'),
        mb_k5e3=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=3,
            kernel_size=5,
            type='MBBlock'),
        mb_k5e6=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=6,
            kernel_size=5,
            type='MBBlock'),
        mb_k7e3=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=3,
            kernel_size=7,
            type='MBBlock'),
        mb_k7e6=dict(
            act_cfg=dict(type='ReLU6'),
            expand_ratio=6,
            kernel_size=7,
            type='MBBlock')),
    type='OneShotMutableOP')
arch_setting = [
    [
        24,
        1,
        1,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                mb_k3e1=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=1,
                    kernel_size=3,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
    [
        32,
        4,
        2,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                identity=dict(type='Identity'),
                mb_k3e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k3e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k5e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k5e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k7e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=7,
                    type='MBBlock'),
                mb_k7e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=7,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
    [
        56,
        4,
        2,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                identity=dict(type='Identity'),
                mb_k3e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k3e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k5e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k5e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k7e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=7,
                    type='MBBlock'),
                mb_k7e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=7,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
    [
        112,
        4,
        2,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                identity=dict(type='Identity'),
                mb_k3e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k3e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k5e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k5e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k7e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=7,
                    type='MBBlock'),
                mb_k7e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=7,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
    [
        128,
        4,
        1,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                identity=dict(type='Identity'),
                mb_k3e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k3e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k5e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k5e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k7e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=7,
                    type='MBBlock'),
                mb_k7e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=7,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
    [
        256,
        4,
        2,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                identity=dict(type='Identity'),
                mb_k3e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k3e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k5e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k5e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k7e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=7,
                    type='MBBlock'),
                mb_k7e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=7,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
    [
        432,
        1,
        1,
        dict(
            _scope_='mmrazor',
            candidates=dict(
                identity=dict(type='Identity'),
                mb_k3e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k3e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=3,
                    type='MBBlock'),
                mb_k5e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k5e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=5,
                    type='MBBlock'),
                mb_k7e3=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=3,
                    kernel_size=7,
                    type='MBBlock'),
                mb_k7e6=dict(
                    act_cfg=dict(type='ReLU6'),
                    expand_ratio=6,
                    kernel_size=7,
                    type='MBBlock')),
            type='OneShotMutableOP'),
    ],
]
dataset_type = 'mmcls.ImageNet'
default_hooks = dict(
    checkpoint=dict(_scope_='mmcls', interval=1, type='CheckpointHook'),
    logger=dict(_scope_='mmcls', interval=100, type='LoggerHook'),
    param_scheduler=dict(_scope_='mmcls', type='ParamSchedulerHook'),
    sampler_seed=dict(_scope_='mmcls', type='DistSamplerSeedHook'),
    timer=dict(_scope_='mmcls', type='IterTimerHook'),
    visualization=dict(
        _scope_='mmcls', enable=False, type='VisualizationHook'))
default_scope = 'mmcls'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
find_unused_parameters = True
launcher = 'none'
load_from = 'my_nas_supernet/epoch_96.pth'
log_level = 'INFO'
model = dict(
    architecture=dict(
        _scope_='mmcls',
        backbone=dict(
            _scope_='mmrazor',
            arch_setting=[
                [
                    24,
                    1,
                    1,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            mb_k3e1=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=1,
                                kernel_size=3,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
                [
                    32,
                    4,
                    2,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            identity=dict(type='Identity'),
                            mb_k3e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k3e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k5e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k5e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k7e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=7,
                                type='MBBlock'),
                            mb_k7e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=7,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
                [
                    56,
                    4,
                    2,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            identity=dict(type='Identity'),
                            mb_k3e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k3e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k5e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k5e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k7e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=7,
                                type='MBBlock'),
                            mb_k7e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=7,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
                [
                    112,
                    4,
                    2,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            identity=dict(type='Identity'),
                            mb_k3e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k3e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k5e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k5e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k7e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=7,
                                type='MBBlock'),
                            mb_k7e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=7,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
                [
                    128,
                    4,
                    1,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            identity=dict(type='Identity'),
                            mb_k3e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k3e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k5e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k5e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k7e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=7,
                                type='MBBlock'),
                            mb_k7e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=7,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
                [
                    256,
                    4,
                    2,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            identity=dict(type='Identity'),
                            mb_k3e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k3e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k5e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k5e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k7e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=7,
                                type='MBBlock'),
                            mb_k7e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=7,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
                [
                    432,
                    1,
                    1,
                    dict(
                        _scope_='mmrazor',
                        candidates=dict(
                            identity=dict(type='Identity'),
                            mb_k3e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k3e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=3,
                                type='MBBlock'),
                            mb_k5e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k5e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=5,
                                type='MBBlock'),
                            mb_k7e3=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=3,
                                kernel_size=7,
                                type='MBBlock'),
                            mb_k7e6=dict(
                                act_cfg=dict(type='ReLU6'),
                                expand_ratio=6,
                                kernel_size=7,
                                type='MBBlock')),
                        type='OneShotMutableOP'),
                ],
            ],
            first_channels=40,
            last_channels=1728,
            type='SearchableMobileNetV2',
            widen_factor=1.0),
        data_preprocessor=dict(
            mean=[
                123.675,
                116.28,
                103.53,
            ],
            std=[
                58.395,
                57.12,
                57.375,
            ],
            to_rgb=True),
        head=dict(
            in_channels=1728,
            loss=dict(
                label_smooth_val=0.1,
                loss_weight=1.0,
                mode='original',
                num_classes=1000,
                type='LabelSmoothLoss'),
            num_classes=1000,
            topk=(
                1,
                5,
            ),
            type='LinearClsHead'),
        neck=dict(type='GlobalAveragePooling'),
        type='ImageClassifier'),
    mutator=dict(type='mmrazor.NasMutator'),
    norm_training=True,
    type='mmrazor.SPOS')
nas_backbone = dict(
    _scope_='mmrazor',
    arch_setting=[
        [
            24,
            1,
            1,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    mb_k3e1=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=1,
                        kernel_size=3,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
        [
            32,
            4,
            2,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    identity=dict(type='Identity'),
                    mb_k3e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k3e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k5e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k5e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k7e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=7,
                        type='MBBlock'),
                    mb_k7e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=7,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
        [
            56,
            4,
            2,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    identity=dict(type='Identity'),
                    mb_k3e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k3e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k5e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k5e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k7e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=7,
                        type='MBBlock'),
                    mb_k7e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=7,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
        [
            112,
            4,
            2,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    identity=dict(type='Identity'),
                    mb_k3e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k3e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k5e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k5e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k7e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=7,
                        type='MBBlock'),
                    mb_k7e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=7,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
        [
            128,
            4,
            1,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    identity=dict(type='Identity'),
                    mb_k3e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k3e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k5e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k5e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k7e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=7,
                        type='MBBlock'),
                    mb_k7e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=7,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
        [
            256,
            4,
            2,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    identity=dict(type='Identity'),
                    mb_k3e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k3e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k5e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k5e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k7e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=7,
                        type='MBBlock'),
                    mb_k7e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=7,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
        [
            432,
            1,
            1,
            dict(
                _scope_='mmrazor',
                candidates=dict(
                    identity=dict(type='Identity'),
                    mb_k3e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k3e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=3,
                        type='MBBlock'),
                    mb_k5e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k5e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=5,
                        type='MBBlock'),
                    mb_k7e3=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=3,
                        kernel_size=7,
                        type='MBBlock'),
                    mb_k7e6=dict(
                        act_cfg=dict(type='ReLU6'),
                        expand_ratio=6,
                        kernel_size=7,
                        type='MBBlock')),
                type='OneShotMutableOP'),
        ],
    ],
    first_channels=40,
    last_channels=1728,
    type='SearchableMobileNetV2',
    widen_factor=1.0)
optim_wrapper = dict(
    clip_grad=None,
    optimizer=dict(
        _scope_='mmrazor',
        lr=0.045,
        momentum=0.9,
        type='SGD',
        weight_decay=4e-05),
    paramwise_cfg=dict(
        bias_decay_mult=0.0, dwconv_decay_mult=0.0, norm_decay_mult=0.0))
param_scheduler = dict(
    _scope_='mmrazor',
    by_epoch=True,
    convert_to_iter_based=True,
    end=300,
    eta_min=0.0,
    power=1.0,
    type='PolyLR')
paramwise_cfg = dict(
    bias_decay_mult=0.0, dwconv_decay_mult=0.0, norm_decay_mult=0.0)
preprocess_cfg = dict(
    mean=[
        123.675,
        116.28,
        103.53,
    ],
    std=[
        58.395,
        57.12,
        57.375,
    ],
    to_rgb=True)
randomness = dict(deterministic=False, seed=1234)
resume = False
supernet = dict(
    _scope_='mmcls',
    backbone=dict(
        _scope_='mmrazor',
        arch_setting=[
            [
                24,
                1,
                1,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        mb_k3e1=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=1,
                            kernel_size=3,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
            [
                32,
                4,
                2,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        identity=dict(type='Identity'),
                        mb_k3e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k3e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k5e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k5e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k7e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=7,
                            type='MBBlock'),
                        mb_k7e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=7,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
            [
                56,
                4,
                2,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        identity=dict(type='Identity'),
                        mb_k3e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k3e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k5e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k5e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k7e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=7,
                            type='MBBlock'),
                        mb_k7e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=7,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
            [
                112,
                4,
                2,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        identity=dict(type='Identity'),
                        mb_k3e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k3e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k5e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k5e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k7e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=7,
                            type='MBBlock'),
                        mb_k7e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=7,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
            [
                128,
                4,
                1,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        identity=dict(type='Identity'),
                        mb_k3e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k3e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k5e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k5e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k7e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=7,
                            type='MBBlock'),
                        mb_k7e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=7,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
            [
                256,
                4,
                2,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        identity=dict(type='Identity'),
                        mb_k3e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k3e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k5e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k5e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k7e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=7,
                            type='MBBlock'),
                        mb_k7e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=7,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
            [
                432,
                1,
                1,
                dict(
                    _scope_='mmrazor',
                    candidates=dict(
                        identity=dict(type='Identity'),
                        mb_k3e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k3e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=3,
                            type='MBBlock'),
                        mb_k5e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k5e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=5,
                            type='MBBlock'),
                        mb_k7e3=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=3,
                            kernel_size=7,
                            type='MBBlock'),
                        mb_k7e6=dict(
                            act_cfg=dict(type='ReLU6'),
                            expand_ratio=6,
                            kernel_size=7,
                            type='MBBlock')),
                    type='OneShotMutableOP'),
            ],
        ],
        first_channels=40,
        last_channels=1728,
        type='SearchableMobileNetV2',
        widen_factor=1.0),
    data_preprocessor=dict(
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        std=[
            58.395,
            57.12,
            57.375,
        ],
        to_rgb=True),
    head=dict(
        in_channels=1728,
        loss=dict(
            label_smooth_val=0.1,
            loss_weight=1.0,
            mode='original',
            num_classes=1000,
            type='LabelSmoothLoss'),
        num_classes=1000,
        topk=(
            1,
            5,
        ),
        type='LinearClsHead'),
    neck=dict(type='GlobalAveragePooling'),
    type='ImageClassifier')
test_cfg = dict()
test_dataloader = dict(
    batch_size=56,
    dataset=dict(
        _scope_='mmrazor',
        ann_file='meta/val.txt',
        data_prefix='val',
        data_root='data/imagenet',
        pipeline=[
            dict(_scope_='mmcls', type='LoadImageFromFile'),
            dict(_scope_='mmcls', edge='short', scale=256, type='ResizeEdge'),
            dict(_scope_='mmcls', crop_size=224, type='CenterCrop'),
            dict(_scope_='mmcls', type='PackClsInputs'),
        ],
        type='mmcls.ImageNet'),
    num_workers=10,
    persistent_workers=True,
    sampler=dict(_scope_='mmrazor', shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    _scope_='mmcls', topk=(
        1,
        5,
    ), type='Accuracy')
test_pipeline = [
    dict(_scope_='mmcls', type='LoadImageFromFile'),
    dict(_scope_='mmcls', edge='short', scale=256, type='ResizeEdge'),
    dict(_scope_='mmcls', crop_size=224, type='CenterCrop'),
    dict(_scope_='mmcls', type='PackClsInputs'),
]
train_cfg = dict(
    constraints_range=dict(flops=(
        0.0,
        465.0,
    )),
    dataloader=dict(
        batch_size=56,
        dataset=dict(
            _scope_='mmrazor',
            ann_file='meta/val.txt',
            data_prefix='val',
            data_root='data/imagenet',
            pipeline=[
                dict(_scope_='mmcls', type='LoadImageFromFile'),
                dict(
                    _scope_='mmcls',
                    edge='short',
                    scale=256,
                    type='ResizeEdge'),
                dict(_scope_='mmcls', crop_size=224, type='CenterCrop'),
                dict(_scope_='mmcls', type='PackClsInputs'),
            ],
            type='mmcls.ImageNet'),
        num_workers=10,
        persistent_workers=True,
        sampler=dict(_scope_='mmrazor', shuffle=False, type='DefaultSampler')),
    evaluator=dict(_scope_='mmcls', topk=(
        1,
        5,
    ), type='Accuracy'),
    max_epochs=20,
    mutate_prob=0.1,
    num_candidates=50,
    num_crossover=25,
    num_mutation=25,
    score_key='accuracy/top1',
    top_k=10,
    type='mmrazor.EvolutionSearchLoop')
train_dataloader = dict(
    batch_size=56,
    dataset=dict(
        _scope_='mmrazor',
        ann_file='meta/train.txt',
        data_prefix='train',
        data_root='data/imagenet',
        pipeline=[
            dict(_scope_='mmcls', type='LoadImageFromFile'),
            dict(_scope_='mmcls', scale=224, type='RandomResizedCrop'),
            dict(
                _scope_='mmcls',
                brightness=0.4,
                contrast=0.4,
                saturation=0.4,
                type='ColorJitter'),
            dict(
                _scope_='mmcls',
                direction='horizontal',
                prob=0.5,
                type='RandomFlip'),
            dict(_scope_='mmcls', type='PackClsInputs'),
        ],
        type='mmcls.ImageNet'),
    num_workers=10,
    persistent_workers=True,
    sampler=dict(_scope_='mmrazor', shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(_scope_='mmcls', type='LoadImageFromFile'),
    dict(_scope_='mmcls', scale=224, type='RandomResizedCrop'),
    dict(
        _scope_='mmcls',
        brightness=0.4,
        contrast=0.4,
        saturation=0.4,
        type='ColorJitter'),
    dict(_scope_='mmcls', direction='horizontal', prob=0.5, type='RandomFlip'),
    dict(_scope_='mmcls', type='PackClsInputs'),
]
val_cfg = dict()
val_dataloader = dict(
    batch_size=56,
    dataset=dict(
        _scope_='mmrazor',
        ann_file='meta/val.txt',
        data_prefix='val',
        data_root='data/imagenet',
        pipeline=[
            dict(_scope_='mmcls', type='LoadImageFromFile'),
            dict(_scope_='mmcls', edge='short', scale=256, type='ResizeEdge'),
            dict(_scope_='mmcls', crop_size=224, type='CenterCrop'),
            dict(_scope_='mmcls', type='PackClsInputs'),
        ],
        type='mmcls.ImageNet'),
    num_workers=10,
    persistent_workers=True,
    sampler=dict(_scope_='mmrazor', shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    _scope_='mmcls', topk=(
        1,
        5,
    ), type='Accuracy')
vis_backends = [
    dict(_scope_='mmcls', type='LocalVisBackend'),
]
visualizer = dict(
    _scope_='mmcls',
    type='ClsVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = 'my_nas_search'
